// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNMRMBL6LWn1EldYGBEZ1rqbATDdDjvIU',
    appId: '1:642831902266:web:94c5462900ce007161f703',
    messagingSenderId: '642831902266',
    projectId: 'pankh-app',
    authDomain: 'pankh-app.firebaseapp.com',
    storageBucket: 'pankh-app.firebasestorage.app',
    measurementId: 'G-FZMJ9J5NR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxoW-NrCPvMzhSq27aNK2QYHKKSH0HKA',
    appId: '1:642831902266:android:2b8fcff1974a715761f703',
    messagingSenderId: '642831902266',
    projectId: 'pankh-app',
    storageBucket: 'pankh-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqoWyLbCiaPlj7WwOk6KR5eMlYUCMnkNo',
    appId: '1:642831902266:ios:5b11459b56f841e561f703',
    messagingSenderId: '642831902266',
    projectId: 'pankh-app',
    storageBucket: 'pankh-app.firebasestorage.app',
    iosBundleId: 'com.aaejae.pankh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqoWyLbCiaPlj7WwOk6KR5eMlYUCMnkNo',
    appId: '1:642831902266:ios:5b11459b56f841e561f703',
    messagingSenderId: '642831902266',
    projectId: 'pankh-app',
    storageBucket: 'pankh-app.firebasestorage.app',
    iosBundleId: 'com.aaejae.pankh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNMRMBL6LWn1EldYGBEZ1rqbATDdDjvIU',
    appId: '1:642831902266:web:b8ad90342ee514b961f703',
    messagingSenderId: '642831902266',
    projectId: 'pankh-app',
    authDomain: 'pankh-app.firebaseapp.com',
    storageBucket: 'pankh-app.firebasestorage.app',
    measurementId: 'G-4DL6LDG6Y3',
  );
}
